<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_ruang_model extends CI_Model
{

    public $table = 'm_ruang';
    public $id = 'kdruang';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('a.kdruang,a.ruang,a.kdunit,b.unit,a.iskelas,a.kdkelas,c.kelas,a.harga,a.aktif,ifnull(count(d.kdbed),0) as ttlbed');
        $this->datatables->from('m_ruang a');
        //add this line for join
        $this->datatables->join('m_unit b', 'a.kdunit = b.kdunit');
        $this->datatables->join('m_kelas c', 'a.kdkelas = c.kdkelas');
        $this->datatables->join('m_ruangbed d', 'a.kdruang = d.kdruang', 'LEFT');
        $this->datatables->group_by('a.kdruang');
        $this->datatables->add_column('action', anchor(site_url('m_ruang/read/$1'), '<i class="fal fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm waves-effect waves-themed')) . "
            " . anchor(site_url('m_ruang/update/$1'), '<i class="fal fa-pencil" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-sm waves-effect waves-themed')) . "
                " . anchor(site_url('m_ruang/delete/$1'), '<i class="fal fa-trash" aria-hidden="true"></i>', 'class="btn btn-danger btn-sm waves-effect waves-themed" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'kdruang');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('a.kdruang,a.ruang,a.kdunit,b.unit,a.iskelas,a.kdkelas,c.kelas,a.harga,a.aktif');
        $this->db->from('m_ruang a');
        //add this line for join
        $this->db->join('m_unit b', 'a.kdunit = b.kdunit');
        $this->db->join('m_kelas c', 'a.kdkelas = c.kdkelas');
        $this->db->where('kdruang', $id);
        return $this->db->get()->row();
    }

    function get_bed($id)
    {
        //$this->db->select('a.kdruang,a.ruang,a.kdunit,b.unit,a.iskelas,a.kdkelas,c.kelas,a.harga,a.aktif');
        $this->db->from('m_ruangbed');
        $this->db->where('kdruang', $id);
        return $this->db->get()->result();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('kdruang', $q);
        $this->db->or_like('ruang', $q);
        $this->db->or_like('kdunit', $q);
        $this->db->or_like('iskelas', $q);
        $this->db->or_like('kdkelas', $q);
        $this->db->or_like('harga', $q);
        $this->db->or_like('aktif', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('kdruang', $q);
        $this->db->or_like('ruang', $q);
        $this->db->or_like('kdunit', $q);
        $this->db->or_like('iskelas', $q);
        $this->db->or_like('kdkelas', $q);
        $this->db->or_like('harga', $q);
        $this->db->or_like('aktif', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    function insbed($data)
    {
        $this->db->insert('m_ruangbed', $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file M_ruang_model.php */
/* Location: ./application/models/M_ruang_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-20 17:28:54 */
/* http://harviacode.com */
