<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pendaftaran_model extends CI_Model
{

    public $table = 't_daftar';
    public $id = 'idreg';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get m_pasien
    function tap($tap)
    {
        $this->db->like('nomr', $tap);
        $this->db->or_like('nik', $tap);
        $this->db->or_like('hp', $tap);
        return $this->db->get('m_pasien')->row();
    }

    //cara bayar
    function metodebayar()
    {
        $this->db->where('aktif', 'Y');
        return $this->db->get('m_bayar_metode')->result();
    }
    function get_bayar($metode)
    {
        $this->db->where('kdmetodebayar', $metode);
        $this->db->where('aktif', 'Y');
        return $this->db->get('m_bayar')->result();
    }
    function get_poli($unit)
    {
        $this->db->where('kdunit', $unit);
        return $this->db->get('m_poli')->result();
    }
    function get_ruang($unit)
    {
        $this->db->where('kdunit', $unit);
        return $this->db->get('m_ruang')->result();
    }
    function get_bed($id)
    {
        $this->db->where('kdruang', $id);
        $this->db->where('aktif', 'Y');
        return $this->db->get('m_ruangbed')->result();
    }
    function get_jadwaldokter($id, $unit)
    {
        //$dtf = date_format(now(), '%w');
        $originalDate = date("Y-m-d");
        $newDate = date("%w", strtotime($originalDate));
        $this->db->select('a.kdjadwal,a.kddokter,b.dokter,TIME_FORMAT(a.jam_mulai, "%H:%i") AS jam_mulai,TIME_FORMAT(a.jam_akhir, "%H:%i") as jam_akhir,a.kode');
        $this->db->from('m_dokterjadwal a');
        $this->db->join('m_dokter b', 'a.kddokter=b.kddokter', 'LEFT');
        $this->db->where('a.kdunit', $unit);
        $this->db->where('a.kode', $id);
        $this->db->where('a.hari', $newDate);
        return $this->db->get()->result();
    }
    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('idreg', $q);
        $this->db->or_like('noreg', $q);
        $this->db->or_like('nobill', $q);
        $this->db->or_like('nomr', $q);
        $this->db->or_like('baru', $q);
        $this->db->or_like('kddokter', $q);
        $this->db->or_like('kdpoli', $q);
        $this->db->or_like('kdbayar', $q);
        $this->db->or_like('rujukan', $q);
        $this->db->or_like('kdrujuk', $q);
        $this->db->or_like('tglreg', $q);
        $this->db->or_like('id_users', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idreg', $q);
        $this->db->or_like('noreg', $q);
        $this->db->or_like('nobill', $q);
        $this->db->or_like('nomr', $q);
        $this->db->or_like('baru', $q);
        $this->db->or_like('kddokter', $q);
        $this->db->or_like('kdpoli', $q);
        $this->db->or_like('kdbayar', $q);
        $this->db->or_like('rujukan', $q);
        $this->db->or_like('kdrujuk', $q);
        $this->db->or_like('tglreg', $q);
        $this->db->or_like('id_users', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Pendaftaran_model.php */
/* Location: ./application/models/Pendaftaran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-22 12:39:41 */
/* http://harviacode.com */
