<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Billing_model extends CI_Model
{

    public $table = 'm_bayar';
    public $id = 'kdbayar';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function json()
    {
        $this->db->select('idreg,noreg,baru,dokter,bayar,rujukan,kdrujuk,tglreg,full_name as petugas,nomr,nik,nama,tgllhr,alamat,kodepos,kdklmn,kdkawin,hp,tglinput,kelamin,kawin,poli,unit');
        $this->db->from('v_pendaftaran');
        $this->db->group_by('noreg');
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($noreg)
    {
        $this->db->from('v_pendaftaran');
        $this->db->where('noreg', $noreg);
        return $this->db->get()->row();
    }
    function get_carabayar()
    {
        $hasil = $this->db->query("SELECT a.kdbayar,a.bayar,a.kdmetodebayar,b.metode FROM m_bayar a
        LEFT JOIN m_bayar_metode b ON a.kdmetodebayar=b.kdmetodebayar
        WHERE a.aktif='Y' AND b.aktif='Y'");
        return $hasil->result();
    }
    function get_keringanan($noreg)
    {
        $hasil = $this->db->query("SELECT * from t_keringanan where noreg='$noreg'");
        return $hasil->row();
    }
    //////////////////////////////////////////////
    // function billing($noreg)
    // {
    //     $hasil = $this->db->query("SELECT *,a.harga as hargas,d.* FROM t_billrajal a LEFT JOIN m_tarif b on a.kdtarif=b.kdtarif LEFT JOIN m_tarif bb ON bb.kdtarif=b.kdtarif LEFT JOIN m_poli c on b.kdpoli=c.kdpoli LEFT JOIN m_bayar d ON a.kdbayar=d.kdbayar where a.noreg='$noreg'");
    //     return $hasil->result();
    // }
    function billing($noreg)
    {
        $this->db->from('v_bill');
        $this->db->where('noreg', $noreg);
        return $this->db->get()->result();
    }
    function billing_total($noreg)
    {
        $this->db->select('kdmetodebayar,bayar,sum(ttl) as ttl');
        $this->db->from('v_bill');
        $this->db->where('noreg', $noreg);
        $this->db->group_by('kdbayar');
        return $this->db->get()->result();
    }
    function billing_bayar($noreg)
    {
        $this->db->select('nobill,noreg,kdmetodebayar,bayar,sum(ttl) as ttl');
        $this->db->from('v_bill');
        $this->db->where('noreg', $noreg);
        $this->db->where_not_in('kdmetodebayar', '1');
        return $this->db->get()->result();
    }
    //////////////////////obat////////////////////////////////////
    function billing_obat($noreg)
    {
        $hasil = $this->db->query("SELECT a.*,b.nmobat,d.*FROM t_billobat a
                LEFT JOIN m_obat b ON a.kdobat=b.kdobat LEFT JOIN m_bayar d ON a.kdbayar=d.kdbayar where a.noreg='$noreg'");
        return $hasil->result();
    }
    function billing_obat_total($noreg)
    {
        $hasil = $this->db->query("SELECT SUM(a.hargaobat*qty) as total FROM t_billobat a
                LEFT JOIN m_obat b ON a.kdobat=b.kdobat LEFT JOIN m_bayar d ON a.kdbayar=d.kdbayar where a.noreg='$noreg'");
        return $hasil->row();
    }
    function updatecarabayar($nobill, $noreg, $kdbayar, $kode, $resep)
    {
        if ($resep == 'N') {
            $hasil = $this->db->query("update t_billrajal set kdbayar='$kdbayar' where noreg='$noreg' and nobill='$nobill' and kdtarif='$kode'");
        } else {
            $hasil = $this->db->query("update t_billobat set kdbayar='$kdbayar' where noreg='$noreg' and nobill='$nobill' and kdobat='$kode'");
        }
        return $hasil;
    }
    function ins_billbayar($nobayar, $nobill, $noreg, $jmlbayar, $tglinput, $id_users)
    {
        $hasil = $this->db->query("INSERT INTO t_billbayar (nobayar,nobill, noreg, jmlbayar, status,tglinput, id_users)VALUES('$nobayar','$nobill','$noreg','$jmlbayar','L','$tglinput','$id_users')");
        $hasil = $this->db->query("update t_billrajal set status='L',nobayar='$nobayar' where noreg='$noreg'");
        $hasil = $this->db->query("update t_billobat set status='L',nobayar='$nobayar' where noreg='$noreg'");
        $hasil = $this->db->query("update t_keringanan set nobayar='$nobayar' where noreg='$noreg'");
        return $hasil;
    }
    function ins_keringanan($kdkeringanan, $alasan, $noreg, $jml, $tglinput, $id_users)
    {
        $hasil = $this->db->query("INSERT INTO t_keringanan (kdkeringanan,alasan, noreg, jml, tglinput, id_users)VALUES('$kdkeringanan','$alasan','$noreg','$jml','$tglinput','$id_users')");
        return $hasil;
    }
}

/* End of file M_bayar_model.php */
/* Location: ./application/models/M_bayar_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-11-22 04:06:22 */
/* http://harviacode.com */
