<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_pasien_model extends CI_Model
{

    public $table = 'm_pasien';
    public $id = 'nomr';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('nomr,nik,nama,tgllhr,alamat,kodepos,kdklmn,kdkawin,hp,tglinput,kelamin,kawin,full_name');
        $this->datatables->from('v_pasien');
        //add this line for join
        $this->datatables->add_column('action', anchor(site_url('m_pasien/read/$1'), '<i class="fal fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-xs waves-effect waves-themed')) . "
            " . anchor(site_url('m_pasien/update/$1'), '<i class="fal fa-pencil" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-xs waves-effect waves-themed')) . "
                " . anchor(site_url('t_daftar/metode_bayar/N/$1'), '<i class="fal fa-first-aid" aria-hidden="true"> Daftar</i>', array('class' => 'btn btn-success btn-xs waves-effect waves-themed')), 'nomr');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('nomr', $q);
        $this->db->or_like('nik', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('tgllhr', $q);
        $this->db->or_like('alamat', $q);
        $this->db->or_like('kodepos', $q);
        $this->db->or_like('kdklmn', $q);
        $this->db->or_like('kdkawin', $q);
        $this->db->or_like('hp', $q);
        $this->db->or_like('foto', $q);
        $this->db->or_like('tglinput', $q);
        $this->db->or_like('id_users', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('nomr', $q);
        $this->db->or_like('nik', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('tgllhr', $q);
        $this->db->or_like('alamat', $q);
        $this->db->or_like('kodepos', $q);
        $this->db->or_like('kdklmn', $q);
        $this->db->or_like('kdkawin', $q);
        $this->db->or_like('hp', $q);
        $this->db->or_like('foto', $q);
        $this->db->or_like('tglinput', $q);
        $this->db->or_like('id_users', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file M_pasien_model.php */
/* Location: ./application/models/M_pasien_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-10-22 07:48:27 */
/* http://harviacode.com */
