<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_radhasil_model extends CI_Model
{

    public $table = 't_radhasil';
    public $id = 'nobill';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('nobill,noreg,kdtarif,hasil,tglinput,id_users');
        $this->datatables->from('t_radhasil');
        //add this line for join
        //$this->datatables->join('table2', 't_radhasil.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('t_radhasil/read/$1'), '<i class="fal fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm waves-effect waves-themed')) . "
            " . anchor(site_url('t_radhasil/update/$1'), '<i class="fal fa-pencil" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-sm waves-effect waves-themed')) . "
                " . anchor(site_url('t_radhasil/delete/$1'), '<i class="fal fa-trash" aria-hidden="true"></i>', 'class="btn btn-danger btn-sm waves-effect waves-themed" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'nobill');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($noreg)
    {
        $this->db->select('*');
        $this->db->from('v_pendaftaran');
        //$this->datatables->join('m_pasien', 't_daftar.nomr = m_pasien.nomr');
        $this->db->where('noreg', $noreg);
        //return $this->db->get($this->table)->row();
        return $this->db->get()->row();
    }

    function get_tindakan_rad($noreg, $nobill)
    {
        $this->db->select('a.noreg,b.kdtarif,b.nmtarif,a.nobill as radbill,c.hasil');
        $this->db->from('t_billrajal a');
        $this->db->JOIN('m_tarif b', 'a.kdtarif=b.kdtarif', 'LEFT');
        $this->db->JOIN('t_radhasil c', 'a.nobill=c.nobill', 'LEFT');
        $this->db->where('b.kdpoli', '4');
        $this->db->where('a.nobill', $nobill);
        $this->db->where('a.noreg', $noreg);
        $hasil = $this->db->get();
        return $hasil->result();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('nobill', $q);
        $this->db->or_like('noreg', $q);
        $this->db->or_like('kdtarif', $q);
        $this->db->or_like('hasil', $q);
        $this->db->or_like('tglinput', $q);
        $this->db->or_like('id_users', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('nobill', $q);
        $this->db->or_like('noreg', $q);
        $this->db->or_like('kdtarif', $q);
        $this->db->or_like('hasil', $q);
        $this->db->or_like('tglinput', $q);
        $this->db->or_like('id_users', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    public function getRows($nobill, $noreg, $kdtarif)
    {
        $this->db->select('id,file_name,uploaded_on');
        $this->db->from('t_rad_file');
        $this->db->where('nobill', $nobill);
        $this->db->where('noreg', $noreg);
        $this->db->where('kdtarif', $kdtarif);
        // if ($id) {
        //     $this->db->where('id', $id);
        //     $query = $this->db->get();
        //     $result = $query->row_array();
        // } else {
        $this->db->order_by('uploaded_on', 'desc');
        $query = $this->db->get();
        $result = $query->result_array();
        //}
        return !empty($result) ? $result : false;
    }

    /*
     * Insert file data into the database
     * @param array the data for inserting into the table
     */
    public function upload($data = array())
    {
        $insert = $this->db->insert_batch('t_rad_file', $data);
        return $insert ? true : false;
    }
}

/* End of file T_radhasil_model.php */
/* Location: ./application/models/T_radhasil_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-11-21 06:44:33 */
/* http://harviacode.com */
